### ISSUE TITLE
用户名称长度超过4个字后，显示效果不好

### ISSUE THREAD

**Issue by birdma** [limijiaoyin/bvod-portal#259]
![bug](https://cloud.githubusercontent.com/assets/7031924/5234005/e4ed878e-77e6-11e4-9212-13fd42481dc9.png)

**Comment by JilinXie** [comment]
Well, Chinese character is actually forbiden
![image](https://cloud.githubusercontent.com/assets/5516431/5717527/fe60fccc-9b3c-11e4-8e9f-d22a9b218178.png)

So, please provide sound information for reproducing the problem
