### ISSUE TITLE
没上传封面时的默认图片换一个图片吧

### ISSUE THREAD

**Issue by birdma** [limijiaoyin/bvod-portal#287]
![bvod3](https://cloud.githubusercontent.com/assets/7031924/5502302/c7062c5a-87a2-11e4-8e9b-fb05703c6aeb.png)

**Comment by birdma** [comment]
默认封面图：
https://drive.google.com/open?id=0B0y4IERFZp2UbzhVTzVWbld4YU8zLUN3VmJvRXY3Z0stUEl3&authuser=0

**Comment by JilinXie** [comment]
The size of this image is not matching the original,, better provide one of size 234x134

**Comment by birdma** [comment]
比例是相同的，可以直接使用，试一把？
