### ISSUE TITLE
搜索部门时崩溃，观看人数不显示

### ISSUE THREAD

**Issue by starding** [limijiaoyin/bvod-portal#304]
如题

**Comment by talentsun** [comment]
这是两个问题，最好开两个 issues

On Tue, Jul 21, 2015 at 7:26 PM, starding <notifications@github.com> wrote:

> 如题
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/limijiaoyin/bvod-portal/issues/304>.
>



-- 
*Qiao Sun (孙桥)*
Limijiaoyin | CEO
Mobile: 18618170688
QQ: 2851766350
Weibo: weibo.com/bridgesun
